name: Update README with Last Pushed Repo

on:
  push:
    branches:
      - main # Replace with your default branch
  schedule:
    - cron: '*/10 * * * *' # Runs daily (optional, adjust as needed)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Get the most recently updated repository
      - name: Fetch last pushed repository
        id: fetch_repo
        run: |
          LAST_REPO=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/user/repos?sort=pushed&per_page=1" | jq -r '.[0]')
          echo "REPO_NAME=$(echo $LAST_REPO | jq -r '.name')" >> $GITHUB_ENV
          echo "REPO_URL=$(echo $LAST_REPO | jq -r '.html_url')" >> $GITHUB_ENV

      # Update README.md
      - name: Update README.md
        run: |
          sed -i "s|## Currently Working On:.*|## Currently Working On: [${REPO_NAME}](${REPO_URL})|" README.md

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with last pushed repository"
          git push
