name: Update README with Last Pushed Repo

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the main branch.

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Get Last Pushed Repository
      - name: Get Last Pushed Repository
        id: last-repo
        run: |
          LAST_REPO=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/users/${{ github.actor }}/events \
            | jq -r 'map(select(.type == "PushEvent")) | .[0].repo.name')
          echo "LAST_REPO=${LAST_REPO}" >> $GITHUB_ENV

      # Step 3: Update README.md
      - name: Update README
        run: |
          sed -i "s|## Currently Working On: \[.*\](.*)|## Currently Working On: [${{ env.LAST_REPO }}](https://github.com/${{ github.actor }}/${{ env.LAST_REPO }})|" README.md

      # Step 4: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "Update Currently Working On section"
          git push
